Ordering of different types
neo4j/neo4j-documentation pull request #1014
Opened 2021-03-08 20:01 UTC by hedengran

Adds details on how ordering is defined between different types.

2021-03-09 10:05 UTC, sherfert requested changes

2021-03-09 10:05 UTC, sherfert commented on cypher/cypher-docs/src/docs/dev/syntax/comparison.asciidoc
> +   **** <<cypher-map-projection, `RELATIONSHIP` maps>>
A discussion in CLG concluded some time ago that we want to move away from nodes and relationships being seen as `Maps`. This is also only present in opencypher documents, but not in our [type documentation](https://neo4j.com/docs/cypher-manual/current/syntax/values/)

I suggest we make this a flat instead:
```suggestion
  *** <<cypher-literal-maps, Maps>>
  *** <<???, Nodes>>
  *** <<???, Relationships>>
```

The link to `cypher-map-projection` seems unrelated, I suggest linking here instead for nodes and relationships: https://neo4j.com/docs/cypher-manual/current/syntax/values/#structural-types

2021-03-09 10:05 UTC, sherfert commented on cypher/cypher-docs/src/docs/dev/syntax/comparison.asciidoc
> + ** For the container types, elements of the containers use orderability to determine the order between them.
I don't think "orderability" is a phrase introduced anywhere in our documentation. Consider phrasing it more like "the elements of the container type are compared pairwise for ordering and thus determine the ordering of two container types ..."

I think this is orthogonal to the change with `*Ordering* of values with *different* types`. Ordering of container types could be its own bullet point with sub-bullet-points for lists and maps. We also seem to call them [Composite](https://neo4j.com/docs/cypher-manual/current/syntax/values/#composite-types) types and not container types.

2021-03-09 10:05 UTC, sherfert commented on cypher/cypher-docs/src/docs/dev/syntax/comparison.asciidoc
> +  *** <<cypher-lists, `LIST`>>
We don't seem to use UPPERCASE for our types in any other place, But rather CamelCase, e.g. here: https://neo4j.com/docs/cypher-manual/current/syntax/temporal/#cypher-temporal-introduction

2021-03-11 09:44 UTC, sherfert approved these changes

2021-03-12 16:20 UTC, davidoliverSP2 commented
We suspect that the builds for this PR will go green when #1015 is merged. I'll review this once we have completed that PR.

2021-03-15 16:17 UTC, davidoliverSP2 approved these changes
Thanks @hedengran

2021-03-15 16:17 UTC, merged