Add paragraph about needing privileges to create and drop indexes and constraints
neo4j/neo4j-documentation pull request #1157
Opened 2021-07-05 08:35 UTC by Hunterness

Also update sentence about `IF NOT EXISTS`.

2021-07-07 12:21 UTC, AlexicaWright reviewed
Same comments as in the previous versions of this PR :)

2021-07-07 12:21 UTC, AlexicaWright commented on cypher/cypher-docs/src/docs/dev/ql/administration/constraints/index.asciidoc
> +It may still throw an error should there exist conflicting data, indexes, or constraints.
```suggestion
It may still throw an error if conflicting data, indexes, or constraints exist.
```

2021-07-07 12:21 UTC, AlexicaWright commented on cypher/cypher-docs/src/docs/dev/ql/administration/constraints/index.asciidoc
> +while dropping a constraint require <<administration-security-administration-database-constraints, the `DROP CONSTRAINT` privilege>> and
```suggestion
while dropping a constraint requires <<administration-security-administration-database-constraints, the `DROP CONSTRAINT` privilege>> and
```

2021-07-07 12:21 UTC, AlexicaWright commented on cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
> +It may still throw an error should there exist conflicting data or constraints.
```suggestion
It may still throw an error if conflicting data or constraints exist.
```

2021-07-07 12:21 UTC, AlexicaWright commented on cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
> +while dropping an index require <<administration-security-administration-database-indexes, the `DROP INDEX` privilege>> and
```suggestion
while dropping an index requires <<administration-security-administration-database-indexes, the `DROP INDEX` privilege>> and
```

2021-07-08 06:32 UTC, Lojjs requested changes
See comments on 4.1 version, they apply here also.

2021-07-08 09:19 UTC, Lojjs approved these changes

2021-07-08 10:55 UTC, merged