Add some node pattern predicates examples
neo4j/neo4j-documentation pull request #1231
Opened 2021-08-24 14:23 UTC by inmost-light

2021-08-26 06:51 UTC, tobias-johansson requested changes
Looks good! I just have one small spelling/grammar suggestion.

2021-08-26 06:51 UTC, tobias-johansson commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/WhereTest.scala
> +          p("`WHERE` clause can appear inside a node pattern in `MATCH` clause or pattern comprehension:")
```suggestion
          p("`WHERE` can appear inside a node pattern in a `MATCH` clause or a pattern comprehension:")
```

2021-08-31 07:58 UTC, martin-neotech approved these changes
This is great! Did not know that Cypher could do that.

2021-08-31 08:13 UTC, inmost-light commented
@martin-neotech 
That's new in 4.4.

2021-08-31 11:51 UTC, tobias-johansson approved these changes

2021-09-01 09:12 UTC, merged