Update constraint syntax
neo4j/neo4j-documentation pull request #1238
Opened 2021-08-31 09:49 UTC by HannesSandberg

Syntax changed to `FOR ... REQUIRE` instead of `ON ... ASSERT`

2021-08-31 09:59 UTC, HannesSandberg commented
Should we add `FOR` & `REQUIRE` to the list of reserved keywords?

2021-08-31 15:10 UTC, Hunterness commented
CIP: https://github.com/opencypher/openCypher/pull/166 (and just the updates we did https://docs.google.com/document/d/1LemTgk1hcWQhSlFl9jEsiKciYyBV2yf_XVDgKzt29RI/edit?usp=sharing I believe)

2021-09-01 16:10 UTC, Lojjs requested changes
Overall it looks good, only file I found which you should also consider updating is PrettifierTest.scala. And then I have some smaller thoughts I put in the comments. 

I have built the Cypher manual and confirmed everything looks ok, not sure how to build the refcard these days though.

2021-09-01 16:10 UTC, Lojjs commented on cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
> +New syntax for creating constraints, applicable to all constraint types.
Not really sure about this one, but I wonder if we should change the 2 constraint entries just above as well:

1. CREATE CONSTRAINT [constraint_name]... 
Should this have the new FOR .. REQUIRE syntax as well? From the users points of view we will be introducing both changes simultaneously so perhaps it is more helpful with the new syntax there? Or what do you think? 

2. DROP CONSTRAINT...
This one look weird/wrong to me. Wasn't all DROP CONSTRAINT by schema commands deprecated long before 4.4?

2021-09-01 16:10 UTC, Lojjs commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ConstraintsTest.scala
> +      assertions = _ => hasNodeConstraint("Book", "title")
For completeness, do you think we should also have examples with the even more deprecated `CREATE CONSTRAINT ON (book:Book) ASSERT exists(book.title)` as well? 

Same for relationship existence constraints.

2021-09-01 16:10 UTC, Lojjs commented on cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
> +----
We should also update the replacements of `CREATE CONSTRAINT ... ASSERT exists()` below to this, so users don't have to migrate in two steps

2021-09-02 06:55 UTC, HannesSandberg commented on cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
> +New syntax for creating constraints, applicable to all constraint types.
1. makes sense.

2. I don't know. Is there a easier way to find out when than using git blame? Trello?

2021-09-02 07:01 UTC, HannesSandberg commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ConstraintsTest.scala
> +      assertions = _ => hasNodeConstraint("Book", "title")
Sure, might be useful if someone want to figure out the difference between new and old syntax while updating.

2021-09-02 07:43 UTC, Hunterness commented
> Overall it looks good, only file I found which you should also consider updating is PrettifierTest.scala.

There are three such files, but I think I remember something about those being unused so that's why we skipped them (`PrettifierParser` and `PrettifierParserTest` or something like that) (looks like maybe this was what stopped using it: https://github.com/neo4j/neo4j-documentation/pull/889/)

2021-09-02 07:46 UTC, Hunterness commented on cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
> +New syntax for creating constraints, applicable to all constraint types.
2. The drop constraint was deprecated but when we added multi-property uniqueness constraints it got enabled for both create and drop, which is why drop is here with both an added and deprecated label

1. If we update the syntax in the create statement I would prefer to have the syntax update before the uniqueness constraint update in the table

2021-09-02 07:50 UTC, Hunterness commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ConstraintsTest.scala
> +      title = "Create a node property existence constraint using deprecated syntax",
I don't think these can have the same title/name as the other one if we want to show both...

2021-09-02 08:05 UTC, HannesSandberg commented on cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
> +New syntax for creating constraints, applicable to all constraint types.
3. sounds good

2021-09-02 11:18 UTC, Lojjs approved these changes
I'm happy with this now

2021-09-03 12:44 UTC, AlexicaWright approved these changes
Apart from the comment I left, I think this looks good. It's a fairly straightforward update. 👍

2021-09-03 12:44 UTC, AlexicaWright commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ConstraintsTest.scala
> +        "will never contain more than one node with a specific label and one property value.",
```suggestion
        "never contains more than one node with a specific label and one property value.",
```
We like to use present tense and active voice, but I am aware that this has not been consistently implemented, and not in this section either. Perhaps it is better to leave it as is, for consistency's sake.

2021-09-03 12:55 UTC, Lojjs commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ConstraintsTest.scala
> +        "will never contain more than one node with a specific label and one property value.",
Yes, I think this is just copy paste from another test in the same file, so perhaps it is better to make a cleanup card on either your Trello board our ours about updating it across the board.

2021-09-03 12:57 UTC, AlexicaWright commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ConstraintsTest.scala
> +        "will never contain more than one node with a specific label and one property value.",
I agree, it's best dealt with separately. And with that, I have no more objections. Should I merge?

2021-09-03 12:58 UTC, Hunterness commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ConstraintsTest.scala
> +        "will never contain more than one node with a specific label and one property value.",
please do :)

2021-09-03 13:00 UTC, merged