Update documentation to use point.distance instead of distance
neo4j/neo4j-documentation pull request #1266
Opened 2021-10-12 08:56 UTC by pontusmelke

The function `distance` has been deprecated and is replaced by `point.distance`.  This PR tries adds a deprecation section about the distance function and change the documentation so that it uses the new function instead.

Please let me know if you know of any other places to update.

NOTE: This PR will be red until https://github.com/neo-technology/neo4j/pull/12537 has been merged.

2021-10-12 13:52 UTC, pontusmelke commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add new method for bounding box contains for points](https://trello.com/c/Y7hltkd6/3064-add-new-method-for-bounding-box-contains-for-points)

2021-10-15 15:22 UTC, davidoliverSP2 requested changes
Thanks @pontusmelke 

One small typo that was causing some asciidoc syntax to leak into the output. (I'm happy to commit & merge)

2021-10-15 15:22 UTC, davidoliverSP2 commented on cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
> +[[source, cypher, role="noheader"]
```suggestion
[source, cypher, role="noheader"]
```

2021-10-15 15:22 UTC, davidoliverSP2 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SpatialFunctionsTest.scala
> +      function("point.distance(point1, point2)", "A Float.", ("point1", "A point in either a geographic or cartesian coordinate system."), ("point2", "A point in the same CRS as 'point1'."))
```suggestion
      function("point.distance(point1, point2)", "A Float.", ("point1", "A point in either a geographic or cartesian coordinate system."), ("point2", "A point in the same CRS as `point1`."))
```

2021-10-18 08:11 UTC, davidoliverSP2 approved these changes

2021-10-18 10:34 UTC, merged