Document ALTER DATABASE and read-only feature
neo4j/neo4j-documentation pull request #1267
Opened 2021-10-12 08:58 UTC by Lojjs

~~Depends on this product PR: https://github.com/neo-technology/neo4j/pull/12515~~

Manual modelling PR: https://github.com/neo-technology/neo4j-manual-modeling/pull/2420

2021-10-12 12:51 UTC, mnd999 requested changes
Just a few tweaks I think.

2021-10-12 12:51 UTC, mnd999 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +        "The database access can be changed to read-only using the `ALTER DATABASE` command with the sub clause `SET ACCESS READ ONLY`. " +
```suggestion
        "Database access can be changed to read-only using the `ALTER DATABASE` command with the sub clause `SET ACCESS READ ONLY`. " +
```

2021-10-12 12:51 UTC, mnd999 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +        "Thereafter, the database access can be changed back to read-write using the sub clause `SET ACCESS READ WRITE`. " +
```suggestion
        "Subsequently, database access can be changed back to read-write using the sub clause `SET ACCESS READ WRITE`. " +
```

2021-10-12 12:51 UTC, mnd999 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +        "Altering the database access is allowed at all times, whether a database is online or offline. ")
Do we need to add something about what this does? How does it interact with cluster - will nodes that are behind continue to catch up? What happens to write transactions already in progress?

2021-10-12 12:51 UTC, mnd999 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +        "At creation, a database always has read-write access. " +
Is this always true? What about `dbms.databases.default_to_read_only`

2021-10-12 12:51 UTC, mnd999 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +      p("This command is optionally idempotent, with the default behavior to throw an exception if the database does not exists. " +
```suggestion
      p("This command is optionally idempotent, with the default behavior to fail with an error if the database does not exist. " +
```
Maybe don't talk about exceptions, that's more relevant to code.

2021-10-12 12:51 UTC, mnd999 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +        "Appending `IF EXISTS` to the command will ensure that no exception is thrown and nothing happens should the database not exist.")
```suggestion
        "Appending `IF EXISTS` to the command will ensure that no error is returned and nothing happens should the database not exist.")
```

2021-10-12 14:16 UTC, Lojjs commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +        "Altering the database access is allowed at all times, whether a database is online or offline. ")
Yes probably, will need to discuss with @hugofirth if that should be described here or in some clustering place.

2021-10-12 14:27 UTC, Lojjs commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +      p("This command is optionally idempotent, with the default behavior to throw an exception if the database does not exists. " +
I think that is a good point, will update it also for DROP which I stole this from

2021-10-14 15:08 UTC, renetapopova reviewed
Thanks, @Lojjs, and @mnd999! I have some editorial suggestions.

2021-10-14 15:08 UTC, renetapopova commented on cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
> +New Cypher command for admininstering privilege for modifying access of databases.
```suggestion
New Cypher command for administering privilege for modifying access of databases.
```

2021-10-14 15:08 UTC, renetapopova commented on cypher/cypher-docs/src/docs/dev/glossary.asciidoc
> +| <<administration-databases-alter-database, ALTER DATABASE ... [IF EXISTS] SET ACCESS {READ ONLY \| READ WRITE}>>                                                                  | Database       |
The sentence "In this Neo4j version, only the database access can be modified." implies that there are other versions where one can modify other configurations." 
I would suggest changing these two sentences to:
```suggestion
| <<administration-databases-alter-database, ALTER DATABASE ... [IF EXISTS] SET ACCESS {READ ONLY \| READ WRITE}>>                                                                  | Database       | Modifies the database access.
```
And in the next versions, when we add more capabilities to that command we can then change the description to reflect them.

2021-10-14 15:08 UTC, renetapopova commented on cypher/cypher-docs/src/docs/dev/glossary.asciidoc
> +| <<administration-security-administration-dbms-privileges-database-management, DATABASE MANAGEMENT>>     | DBMS                  | Determines whether the user can create, delete and modify databases
```suggestion
| <<administration-security-administration-dbms-privileges-database-management, DATABASE MANAGEMENT>>     | DBMS                  | Determines whether the user can create, delete, and modify databases.
```

2021-10-14 15:08 UTC, renetapopova commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +    synopsis("This chapter explains how to use Cypher to manage Neo4j databases: creating, modifying, deleting, starting and stopping individual databases within a single server.")
```suggestion
    synopsis("This chapter explains how to use Cypher to manage Neo4j databases: creating, modifying, deleting, starting, and stopping individual databases within a single server.")
```

2021-10-14 15:08 UTC, renetapopova commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
>            """Note that the results of this command are filtered according to the `ACCESS` privileges the user has.
```suggestion
          """Note that the results of this command are filtered according to the `ACCESS` privileges of the user.
```

2021-10-14 15:08 UTC, renetapopova commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +            |However, a user with `CREATE/DROP/ALTER DATABASE`, `SET DATABASE ACCESS`, or `DATABASE MANAGEMENT` privileges can see all databases regardless of their `ACCESS` privileges.
```suggestion
            |However, users with `CREATE/DROP/ALTER DATABASE`, `SET DATABASE ACCESS`, or `DATABASE MANAGEMENT` privileges can see all databases regardless of their `ACCESS` privileges.
```

2021-10-14 15:08 UTC, renetapopova commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +          "Appending `IF NOT EXISTS` to the command will ensure that no error is returned and nothing happens should the database already exist. " +
```suggestion
          "Appending `IF NOT EXISTS` to the command ensures that no error is returned and nothing happens should the database already exist. " +
```

2021-10-14 15:08 UTC, renetapopova commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +      p("Databases can be modified using the command `ALTER DATABASE`. In this Neo4j version, the only thing that can be modified is the database access. " +
I wouldn't use "In this Neo4j version,.." as with the next version, this will not be relevant anymore. So, my suggestion is to remove the second sentence and instead say:
_Database access can be modified using the command `ALTER DATABASE`. _
And when we add more capabilities to the `ALTER DATABASE` command, we can then remove access and explain what can be altered.

2021-10-14 15:08 UTC, renetapopova commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +        "Appending `IF EXISTS` to the command will ensure that no error is returned and nothing happens should the database not exist.")
```suggestion
        "Appending `IF EXISTS` to the command ensures that no error is returned and nothing happens should the database not exist.")
```

2021-10-14 15:08 UTC, renetapopova commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +        "Appending `IF EXISTS` to the command will ensure that no error is returned and nothing happens should the database not exist.")
```suggestion
        "Appending `IF EXISTS` to the command ensures that no error is returned and nothing happens should the database not exist.")
```

2021-10-21 13:11 UTC, Lojjs commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +      p("Databases can be modified using the command `ALTER DATABASE`. In this Neo4j version, the only thing that can be modified is the database access. " +
In the manual modelling PR where I explain the privileges, the distinction is actually somewhat important, so there we need to discuss how to phrase it. In this place, what you have suggested works, so I will update the text to that.

2021-10-21 13:51 UTC, renetapopova approved these changes
Thanks, @Lojjs! LGTM from an editorial perspective. Unfortunately, both the TC and my local builds have failed, so I _think_ we need to rebase the branch to see how it looks like.

2021-10-21 14:07 UTC, Lojjs commented
> Thanks, @Lojjs! LGTM from an editorial perspective. Unfortunately, both the TC and my local builds have failed, so I _think_ we need to rebase the branch to see how it looks like.

That is probably because we have not merged the product PR quite yet, there are some problems with the build of it.

2021-10-25 10:43 UTC, renetapopova commented
Hey @Lojjs, shall we merge this one?

2021-10-26 12:51 UTC, renetapopova commented
@mnd999 are you happy with this one? If yes, could you please resolve the conflicts and merge it?

2021-10-26 13:29 UTC, mnd999 commented
@renetapopova Will do so now

2021-10-26 13:30 UTC, renetapopova commented
> @renetapopova Will do so now

Thank you so much!

2021-10-26 14:08 UTC, mnd999 approved these changes

2021-10-26 14:09 UTC, merged