Document point.withinBBox
neo4j/neo4j-documentation pull request #1268
Opened 2021-10-12 10:20 UTC by pontusmelke

Instead of using inequality operators for spatial points queries should now be using the new `point.withinBBox` function.

Builds on top of https://github.com/neo4j/neo4j-documentation/pull/1266

2021-10-12 13:51 UTC, pontusmelke commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add new method for bounding box contains for points](https://trello.com/c/Y7hltkd6/3064-add-new-method-for-bounding-box-contains-for-points)

2021-10-18 08:16 UTC, davidoliverSP2 requested changes
A couple of typos to resolve, and this should build docs cleanly. Will try to build again once I've commit these fixes.

2021-10-18 08:16 UTC, davidoliverSP2 commented on cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
> +[[source, cypher, role="noheader"]
```suggestion
[source, cypher, role="noheader"]
```

2021-10-18 08:16 UTC, davidoliverSP2 commented on cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
> + [[source, cypher, role="noheader"]
```suggestion
 [source, cypher, role="noheader"]
```

2021-10-18 10:40 UTC, davidoliverSP2 commented
@pontusmelke I've just merged #1266 which I think means this PR can be rebased (I suspect the merge conflicts relate to the commits I pushed on that PR, so rebasing here should also resolve those - apologies if I've made this overly complicated though!)
I believe you had some questions about formatting these updates, so we can have a chat once the PR is building cleanly again.

2021-10-22 15:38 UTC, davidoliverSP2 requested changes
Thanks @pontusmelke 

There was an issue with how the table in the _Deprecations, additions and compatibility_ page handled labels, and I've pushed a fix.

I had a few more suggested editorial changes, but these landed in the scala tests. If your hands full next week, I am happy to try and edit the scala tests involved - please do let me know!

2021-10-22 15:38 UTC, davidoliverSP2 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SpatialTest.scala
> +          |The easiest way is to specify the ordering explicitly using for example `point.x`, `point.y` in _cartesian coordinates_ or `point.longitude` and point.latitude` in `geographic coordinates`
We've been working towards moving text-only paragraphs out of scala tests, as it makes it a little too difficult for us to format. Until then though, I would suggest rewording this section to:

----
Comparability and orderability 

The comparability and orderability of spacial values are due to change in an upcoming future release. This means that queries that rely on the comparison of two points using the inequality operators, `<`, `⇐`, `>`, and `>=`, or the specific order of an `ORDER BY n.point` query will need to be rewritten.

The most efficient way to do this is to explicitly specify the ordering. For example, by using `point.x`, `point.y` in _cartesian coordinates_, or `point.longitude` and `point.latitude` in _geographic coordinates_.

2021-10-22 15:38 UTC, davidoliverSP2 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SpatialFunctionsTest.scala
> +          | The return value will be `true` if the provided point is contained in the bounding box (boundary included) otherwise `false`.
Suggested rewording:

----

`point.withinBBox()` takes the following arguments: 

* The point to check.
* The lower-left (south-west) point of a bounding box.
* The upper-right (or north-east) point of a bounding box. 
 
The return value will be true if the provided point is contained in the bounding box (boundary included), otherwise the return value will be false.

2021-10-22 15:38 UTC, davidoliverSP2 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SpatialFunctionsTest.scala
> +        p("Checking if a point in _Cartesian_ CRS is contained in the bounding box.")
I think this paragraph can go above the code example (same with the subsequent examples)

2021-10-22 15:39 UTC, davidoliverSP2 commented on cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
> +Please instea use:
```suggestion
Please instead use:
```

2021-10-27 11:35 UTC, pontusmelke commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SpatialFunctionsTest.scala
> +          | The return value will be `true` if the provided point is contained in the bounding box (boundary included) otherwise `false`.
👍  please verify that I got formatting right?

2021-10-27 11:37 UTC, pontusmelke commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SpatialFunctionsTest.scala
> +        p("Checking if a point in _Cartesian_ CRS is contained in the bounding box.")
All the other examples in this file have `p("...")` just before the `resultTable()`?

2021-10-28 14:10 UTC, davidoliverSP2 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SpatialFunctionsTest.scala
> +        p("Checking if a point in _Cartesian_ CRS is contained in the bounding box.")
ah yep - best to be consistent 👍

2021-10-28 14:40 UTC, davidoliverSP2 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SpatialFunctionsTest.scala
> +          | The return value will be `true` if the provided point is contained in the bounding box (boundary included) otherwise `false`.
Thanks! one small edit to fix the line below the bullets.

2021-10-28 14:41 UTC, davidoliverSP2 approved these changes

2021-10-28 14:41 UTC, merged