Document `CALL { ... } IN TRANSACTIONS`
neo4j/neo4j-documentation pull request #1271
Opened 2021-10-14 12:39 UTC by tobias-johansson

I decided to put this as a subsection of the `CALL {} (subquery)` clause section, rather than as a top level clause section.

2021-10-19 09:36 UTC, hedengran requested changes
Nice work! Just a few comments. Additionally:

* Should we include some example in the Cypher ref-card?
*  Might be a good time to add the deprecation of periodic commit to `Deprecations, additions and compatibility` as well.

2021-10-19 09:36 UTC, hedengran commented on cypher/cypher-docs/src/docs/dev/general/query-transactions.asciidoc
> +All Cypher queries run within transactions. Modifications done by updating queries are held in memory by the transaction until it is committed, at which point the changes are persisted to disk and be
Missing newline after first sentence.

2021-10-19 09:36 UTC, hedengran commented on cypher/cypher-docs/src/docs/dev/general/query-transactions.asciidoc
> +  * are committed, or rolled back, by the user
I think this might look better, but just my 2 cents. 

```suggestion
- _Explicit_ transactions:
  * are opened by the user.
  * can execute multiple Cypher queries in sequence.
  * are committed, or rolled back, by the user.
```

2021-10-19 09:36 UTC, hedengran commented on cypher/cypher-docs/src/docs/dev/general/query-transactions.asciidoc
> +  * are committed automatically when the query finishes successfully
```suggestion
- _Implicit_ transactions, sometimes called auto-commit transactions or auto transactions:
  * are opened automatically.
  * can execute a single Cypher query.
  * are committed automatically when the query finishes successfully.
```

2021-10-19 09:36 UTC, hedengran commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
> +        Seq("4", "The Cardigans", "1992")
```suggestion
        Seq("4", "The Cardigans", "1992")
        Seq("5", "bob hund", "1991")
```

jk 😉

2021-10-19 09:36 UTC, hedengran commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
> +          #started and committed.""".stripMargin('#'))
Isn't four transactions started and committed? 😲

2021-10-19 09:36 UTC, hedengran commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
> +      }
Should we maybe include an example where `inputRows % batchSize != 0` just to clarify how we deplete the last batch?

2021-10-21 08:49 UTC, tobias-johansson commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
> +        Seq("4", "The Cardigans", "1992")
🤣

2021-10-21 08:50 UTC, tobias-johansson commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
> +          #started and committed.""".stripMargin('#'))
Oops wasn't supposed to have a `OF 1 ROW` in the first example

2021-10-21 08:52 UTC, tobias-johansson commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
> +      }
Yeah, that makes sense. Gives us a good reason to add Bob hund to the csv 👍

2021-10-21 10:44 UTC, hedengran commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
> +        Seq("4", "bob hund", "1991"),
😁

2021-10-21 10:47 UTC, hedengran approved these changes

2021-10-21 10:54 UTC, tobias-johansson commented on cypher/cypher-docs/src/docs/dev/general/query-transactions.asciidoc
> +All Cypher queries run within transactions. Modifications done by updating queries are held in memory by the transaction until it is committed, at which point the changes are persisted to disk and be
It will all be one contiguous paragraph anyway won't it?

2021-10-21 11:31 UTC, hedengran commented on cypher/cypher-docs/src/docs/dev/general/query-transactions.asciidoc
> +All Cypher queries run within transactions. Modifications done by updating queries are held in memory by the transaction until it is committed, at which point the changes are persisted to disk and be
True, but I think that for markup files it's good practice to have each sentence on a new line. It's easier to edit and `diffs` will be a lot easier to look at. This resource even quotes the writing guide for `Neo4j Documentation` (which I didn't know existed): https://asciidoctor.org/docs/asciidoc-recommended-practices/

2021-10-26 14:45 UTC, AlexicaWright reviewed
Some editorial comments.

2021-10-26 14:45 UTC, AlexicaWright commented on cypher/cypher-docs/src/docs/dev/clause.asciidoc
> +|Evaluates a subquery in separate transactions. Typically used when modifying or importing large amounts of data .
```suggestion
|Evaluates a subquery in separate transactions. 
Typically used when modifying or importing large amounts of data.
```

2021-10-26 14:45 UTC, AlexicaWright commented on cypher/cypher-docs/src/docs/dev/general/query-transactions.asciidoc
> +In short, updating queries will always either fully succeed, or not succeed at all.
```suggestion
In short, updating a query always either fully succeeds, or does not succeed at all.
```

2021-10-26 14:45 UTC, AlexicaWright commented on cypher/cypher-docs/src/docs/dev/general/query-transactions.asciidoc
> +Note that, as the transaction holds changes in memory, a query that makes a large number of updates will consequently use large amounts of memory.
```suggestion
[NOTE]
====
A query that makes a large number of updates consequently uses large amounts of memory since the transaction holds changes in memory.
For memory configuration in Neo4j, see the <<operations-manual#memory-configuration, Neo4j Operations Manual -> Memory configuration>>.
====
```

2021-10-26 14:45 UTC, AlexicaWright commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
> +        p("""When the failure occurred, the first transaction had already committed, so the database contains two example nodes""")
```suggestion
        p("""When the failure occurred, the first transaction had already been committed, so the database contains two example nodes""")
```

2021-10-26 14:45 UTC, AlexicaWright commented on cypher/cypher-docs/src/docs/dev/general/query-transactions.asciidoc
> +For memory configuration in Neo4j, see the <<operations-manual#memory-configuration, Neo4j Operations Manual -> Memory configuration>>.
```suggestion

```

2021-10-26 14:45 UTC, AlexicaWright commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
> +            |the current inner transaction, and the outer transaction are rolled back.""".stripMargin)
```suggestion
            |both the current inner transaction and the outer transaction are rolled back.""".stripMargin)
```

2021-10-26 14:45 UTC, AlexicaWright commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
> +        p("""If an error occurs in `CALL {} IN TRANSACTIONS` the entire query fails,
```suggestion
        p("""If an error occurs in `CALL {} IN TRANSACTIONS` the entire query fails and
```

2021-10-26 14:45 UTC, AlexicaWright commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
> +        p("""In the following example, the last subquery execution, in the second inner transaction, fails
```suggestion
        p("""In the following example, the last subquery execution in the second inner transaction fails
```

2021-10-26 15:32 UTC, AlexicaWright commented on cypher/cypher-docs/src/docs/dev/clause.asciidoc
> +Typically used when modifying or importing large amounts of data.
May need a pipe?

2021-10-26 15:50 UTC, tobias-johansson commented on cypher/cypher-docs/src/docs/dev/clause.asciidoc
> +Typically used when modifying or importing large amounts of data.
Looks ok in my intellij asciidoc preview

2021-10-26 15:58 UTC, AlexicaWright commented on cypher/cypher-docs/src/docs/dev/clause.asciidoc
> +Typically used when modifying or importing large amounts of data.
I'll trust that, so 👍 from me now!

2021-10-27 06:16 UTC, merged