Adds impersonate privilege to the glossary and 4.4 additions
neo4j/neo4j-documentation pull request #1284
Opened 2021-10-22 15:52 UTC by ncordon

Corrects broken links.

Adds `IMPERSONATE` privilege to the glossary of terms and the new additions to 4.4

2021-10-26 10:38 UTC, mnd999 requested changes

2021-10-26 10:38 UTC, mnd999 commented on cypher/cypher-docs/src/docs/dev/glossary.asciidoc
> +| <<access-control-dbms-administration-impersonation, IMPERSONATE>>                   | DBMS              | Determines whether a user can impersonate another one and assume their privileges.
I think these are supposed to be in alphabetical order, so this one seems out of place.

2021-10-26 10:38 UTC, mnd999 commented on cypher/cypher-docs/src/docs/dev/glossary.asciidoc
> +| <<access-control-dbms-administration-role-management REMOVE ROLE>>                 | DBMS                  | Determines whether the user can revoke roles.
I think you are missing a comma.

2021-10-27 15:31 UTC, mnd999 approved these changes
Looks good now

2021-10-28 09:34 UTC, davidoliverSP2 approved these changes
Thank @ncordon 

👍

2021-10-28 09:34 UTC, merged