Document index type hints
neo4j/neo4j-documentation pull request #1292
Opened 2021-10-26 07:19 UTC by hedengran

Depends on https://github.com/neo-technology/neo4j/pull/12687

2021-10-27 08:07 UTC, arnefischereit commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UsingTest.scala
> +          || `USING [BTREE \| TEXT] INDEX  variable:RELATIONSHIP_TYPE(property)`      | `DirectedRelationshipIndexScan`, `UndirectedRelationshipIndexScan`, `DirectedRelationshipIndexSeek`, `Undirecte
```suggestion
          || `USING [BTREE \| TEXT] INDEX variable:RELATIONSHIP_TYPE(property)`       | `DirectedRelationshipIndexScan`, `UndirectedRelationshipIndexScan`, `DirectedRelationshipIndexSeek`, `UndirectedRelationshipIndexSeek`
```

2021-10-27 08:15 UTC, arnefischereit requested changes
Looks good. I have a few improvement suggestions and I fear you will have to rewrite the example for relationship indexes.

2021-10-27 08:15 UTC, arnefischereit commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UsingTest.scala
> +          || `USING [BTREE \| TEXT] INDEX variable:Label(property)`                   | `NodeIndexScan`, `NodeIndexSeek`
I think we also have the (possibly not so useful) variant `USING INDEX SCAN ...`

2021-10-27 08:15 UTC, arnefischereit commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UsingTest.scala
> +          """Using an index hint will never change the result of a query.
I think this can be generalized:
```suggestion
          """Using a hint must never change the result of a query.
```

2021-10-27 08:15 UTC, arnefischereit commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UsingTest.scala
> +            |Please refer to <<query-tuning-indexes>> for more details.""".stripMargin)
An example would be great. But if that is in the linked document, we should be fine.

2021-10-27 08:15 UTC, arnefischereit commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UsingTest.scala
> +      section("Query using a relationship text index hint") {
I do not see a relationship index here but rather a node index. :thinking:

2021-10-27 08:47 UTC, hedengran commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UsingTest.scala
> +          || `USING [BTREE \| TEXT] INDEX variable:Label(property)`                   | `NodeIndexScan`, `NodeIndexSeek`
I don't think we do? It's (as you noted) missing from documentation. Are you thinking of `USING SCAN`?

2021-10-27 09:05 UTC, hedengran commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UsingTest.scala
> +            |Please refer to <<query-tuning-indexes>> for more details.""".stripMargin)
I considered doing an example, but it's hard to make an example without explaining everything that is already covered in `<<query-tuning-indexes>>`. So I'd prefer to have the information in only one place.

2021-10-27 11:02 UTC, arnefischereit commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UsingTest.scala
> +          || `USING [BTREE \| TEXT] INDEX variable:Label(property)`                   | `NodeIndexScan`, `NodeIndexSeek`
Probably I got confused by that.

2021-10-27 11:07 UTC, arnefischereit approved these changes
Comments addressed. Good to go from my perspective.

2021-10-28 09:20 UTC, AlexicaWright reviewed
A small comment only. But the tests are failing so I haven't been able to build it locally.

2021-10-28 09:20 UTC, AlexicaWright commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/UsingTest.scala
> +            |Therefore, a hint with a specified index type is only fulfillable when the planner knows that using an index of the specified type won't change the results.
```suggestion
            |Therefore, a hint with a specified index type is only fulfillable when the planner knows that using an index of the specified type does not change the results.
```

2021-10-29 09:28 UTC, AlexicaWright approved these changes
👍 LGTM!

2021-10-29 09:29 UTC, merged