adding documentation for new alias commands
neo4j/neo4j-documentation pull request #1296
Opened 2021-10-27 17:18 UTC by nadja-muller

Documentation of new alias commands
depending on: https://github.com/neo-technology/neo4j-manual-modeling/pull/2454

Co-authored-by: Hannes Sandberg<hannes.sandberg@neotechnology.com>

2021-10-29 10:06 UTC, mnd999 requested changes
Just a few bits to change

2021-10-29 10:06 UTC, mnd999 commented on cypher/cypher-docs/src/docs/dev/glossary.asciidoc
> +| <<administration-database-aliases-alter-alias, ALTER ALIAS ... [IF EXISTS] SET DATABASE TARGET ...>>                                                                              | Database Alias |
```suggestion
| <<administration-database-aliases-alter-alias, ALTER ALIAS ... [IF EXISTS] SET DATABASE TARGET ...>>                                                                              | Database Alias | Modifies the target of a database alias.
```

2021-10-29 10:06 UTC, mnd999 commented on cypher/cypher-docs/src/docs/dev/glossary.asciidoc
> +| User and role  | Deletes a specified user.
Why the newline?

2021-10-29 10:06 UTC, mnd999 commented on cypher/cypher-docs/src/docs/dev/ql/administration/show-databases-columns.asciidoc
> +|aliases|The aliases of the database name.|{check-mark}|{check-mark}|
```suggestion
|aliases|The names of any aliases the database may have.|{check-mark}|{check-mark}|
```

2021-10-29 10:06 UTC, mnd999 commented on cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-deny-syntax.asciidoc
> +Because in Neo4j {neo4j-version} you can have only one graph per database, this command uses the database name or alias to refer to that graph.
I think this file moved to manual-modeling so this one no longer does anything

2021-10-29 10:06 UTC, mnd999 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +    query("CREATE DATABASE slow WAIT 5 SECONDS", ResultAssertions(r => {
The wait opening paragraph needs a rewrite as the alias commands do not take wait.

2021-10-29 10:06 UTC, mnd999 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +      p("Aliases can be created using `CREATE ALIAS`.")
What is an alias?

2021-10-29 10:06 UTC, mnd999 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +            |* A name is a valid identifier, additionally allowing dots (`main.alias`).
```suggestion
            |* A name is a valid identifier, additionally allowing dots e.g. `main.alias`.
```

2021-10-29 10:06 UTC, mnd999 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +        """An alias can be used as an alternative database name, which can be used in all places where a database name can be used.
Ahh okay, I think this needs to be the introduction.

2021-10-29 10:06 UTC, mnd999 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +        "Inserting `IF NOT EXISTS` after the alias name ensures that no error is returned and nothing happens should the database already exist. " +
```suggestion
        "Inserting `IF NOT EXISTS` after the alias name ensures that no error is returned and nothing happens should a database alias with that name already exist. " +
```

2021-10-29 10:06 UTC, mnd999 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +        "`CREATE OR REPLACE ALIAS` will fail if there exists a database with the same name.")
```suggestion
        "`CREATE OR REPLACE ALIAS` will fail if there is an existing database with the same name.")
```

2021-10-29 10:06 UTC, mnd999 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +        p("This is equivalent to running `DROP ALIAS `northwind` IF EXISTS FOR DATABASE` followed by `CREATE ALIAS `northwind` FOR DATABASE `northwind-graph-2020`.")
![image](https://user-images.githubusercontent.com/1756429/139415473-b0e50b93-b98e-4a5f-b803-05314d4b7b8c.png)
Something funny with your backticks here

2021-10-29 10:06 UTC, mnd999 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +      p("When a database alias has been altered, it will show up in the aliases column provided by the command `SHOW DATABASES`.")
```suggestion
      p("When a database alias has been altered, it will show up in the aliases column for the target database provided by the command `SHOW DATABASES`.")
```

2021-10-29 11:50 UTC, HannesSandberg commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +        p("This is equivalent to running `DROP ALIAS `northwind` IF EXISTS FOR DATABASE` followed by `CREATE ALIAS `northwind` FOR DATABASE `northwind-graph-2020`.")
I takes forever to build on my computer...  :( Could you verify that it looks nice now @nadja-muller ?

2021-10-29 12:23 UTC, HannesSandberg commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +        p("This is equivalent to running `DROP ALIAS `northwind` IF EXISTS FOR DATABASE` followed by `CREATE ALIAS `northwind` FOR DATABASE `northwind-graph-2020`.")
``DROP ALIAS `northwind` IF EXISTS FOR DATABASE`` followed by ``CREATE ALIAS `northwind` FOR DATABASE `northwind-graph-2020` ``

2021-10-29 14:04 UTC, mnd999 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +        p("This is equivalent to running ``DROP ALIAS `northwind` IF EXISTS FOR DATABASE`` followed by ``CREATE ALIAS `northwind` FOR DATABASE `northwind-graph-2020` ``.")
Probably you want `statsOnlyResultTable()` here as well

2021-10-29 15:05 UTC, mnd999 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/DatabasesTest.scala
> +      })) {}
Also missing statsonlyresultstable here: 
![image](https://user-images.githubusercontent.com/1756429/139458408-c6a0eef9-29c8-476a-be83-fd5eecf763b3.png)
Looks a bit odd with one having it and one not.

2021-11-01 09:12 UTC, HannesSandberg commented on cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-deny-syntax.asciidoc
> +Because in Neo4j {neo4j-version} you can have only one graph per database, this command uses the database name or alias to refer to that graph.
Should we delete the file then?

2021-11-01 09:26 UTC, HannesSandberg commented on cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-deny-syntax.asciidoc
> +Because in Neo4j {neo4j-version} you can have only one graph per database, this command uses the database name or alias to refer to that graph.
@davidoliverSP2 I will remove this file, could you please take a look and see if there is a reason for why is it still there?

2021-11-01 11:29 UTC, davidoliverSP2 approved these changes
Thanks @nadja-muller & @HannesSandberg 

A couple of things that I can commit, but otherwise looks good!

2021-11-01 11:29 UTC, davidoliverSP2 commented on cypher/cypher-docs/src/docs/dev/glossary.asciidoc
> +| <<administration-database-aliases-alter-alias, ALTER ALIAS ... [IF EXISTS] SET DATABASE TARGET ...>>                                                                              | Database Alias |
```suggestion
| <<administration-database-aliases-alter-alias, ALTER ALIAS ... [IF EXISTS] SET DATABASE TARGET ...>>                                                                              | Database alias | Modifies the target of a database alias.
```

2021-11-01 11:29 UTC, davidoliverSP2 commented on cypher/cypher-docs/src/docs/dev/glossary.asciidoc
> +| <<administration-database-aliases-create-alias, CREATE [OR REPLACE] ALIAS ... [IF NOT EXISTS] FOR DATABASE ... >>                                                                 | Database Alias |
```suggestion
| <<administration-database-aliases-create-alias, CREATE [OR REPLACE] ALIAS ... [IF NOT EXISTS] FOR DATABASE ... >>                                                                 | Database alias | Creates a new database alias.
```

2021-11-01 11:29 UTC, davidoliverSP2 commented on cypher/cypher-docs/src/docs/dev/glossary.asciidoc
> +| <<administration-database-aliases-drop-alias, DROP ALIAS ... [IF EXISTS] FOR DATABASE>>                                                                                           | Database Alias |
```suggestion
| <<administration-database-aliases-drop-alias, DROP ALIAS ... [IF EXISTS] FOR DATABASE>>                                                                                           | Database alias | Deletes a specified database alias.
```

2021-11-01 11:29 UTC, davidoliverSP2 commented on cypher/cypher-docs/src/docs/dev/ql/administration/security/grant-deny-syntax.asciidoc
> +Because in Neo4j {neo4j-version} you can have only one graph per database, this command uses the database name or alias to refer to that graph.
My apologies @HannesSandberg - the Access Control content should have been removed from this repository a while ago (as Mark confirmed above, this is all now in the manual-modeling repo. 

I should have removed this content myself when completing the re-architecture project. This page, and others can be removed in another PR.

2021-11-01 12:08 UTC, merged