Explain semantics of subqueries
neo4j/neo4j-documentation pull request #1306
Opened 2021-11-15 16:27 UTC by hedengran

2021-11-16 16:09 UTC, blouerat commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
> +    section("Semantics, call-semantics") {
Didn't you mean to have the comma outside the string?
```suggestion
    section("Semantics", "call-semantics") {
```

2021-11-16 16:10 UTC, hedengran commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
> +    section("Semantics, call-semantics") {
Yes. Thank you.

2021-11-16 16:17 UTC, blouerat approved these changes

2021-11-25 08:35 UTC, AlexicaWright reviewed
Just one editorial comment, but I haven't been able to build locally.

2021-11-25 08:35 UTC, AlexicaWright commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
> +          #For the below query, the `CALL` clause will execute three times.
```suggestion
          #For the below query, the `CALL` clause executes three times.
```

2022-01-17 09:22 UTC, martin-neotech commented
@hedengran please rebase

2022-01-17 13:56 UTC, martin-neotech requested changes
Looks good, just some minor changes needed. Thanks

2022-01-17 13:56 UTC, martin-neotech commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
> +              #  RETURN n.count as innerCount
```suggestion
              #  RETURN n.count AS innerCount
```

2022-01-17 13:56 UTC, martin-neotech commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
> +          #""".stripMargin('#'))
```suggestion
      p("Each execution of a `CALL` clause can observe changes from previous executions.")
```

2022-01-17 16:28 UTC, martin-neotech approved these changes

2022-01-17 16:32 UTC, AlexicaWright reviewed
Just a few editorial comments.

2022-01-17 16:32 UTC, AlexicaWright commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
> +          #For the below query, the `CALL` clause will executes three times.
```suggestion
          #For the query below, the `CALL` clause executes three times.
```

2022-01-17 16:32 UTC, AlexicaWright commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallSubqueryTest.scala
> +          #The `CALL` clause is relying on the incoming row ordering to ensure that a correctly linked list is created, so the incoming rows must be ordered with a preceding `ORDER BY`.
```suggestion
          #The `CALL` clause is relying on the incoming row ordering to ensure that a correctly linked list is created, thus the incoming rows must be ordered with a preceding `ORDER BY`.
```

2022-01-19 12:33 UTC, merged