Adds an example of how to use CASE WHEN  as part of WITH
neo4j/neo4j-documentation pull request #1419
Opened 2022-02-03 15:30 UTC by renetapopova

2022-02-07 14:18 UTC, arnefischereit requested changes
I think we should indent differently and maybe you could remove the reference to the labels or provide an example what you mean there.

2022-02-07 14:18 UTC, arnefischereit commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CaseExpressionsTest.scala
> +   p("""Generic conditional expressions may be expressed using the `CASE` construct.
I think the previous indentation worked better.
```suggestion
    p("""Generic conditional expressions may be expressed using the `CASE` construct.
```

2022-02-07 14:18 UTC, arnefischereit commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CaseExpressionsTest.scala
> +       #For example, instead of specifying the node directly, you can set a property for a node selected by an expression:""".stripMargin('#'))
Indentation:
```suggestion
          #For example, instead of specifying the node directly, you can set a property for a node selected by an expression:""".stripMargin('#'))
```

2022-02-07 14:18 UTC, arnefischereit commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CaseExpressionsTest.scala
> +      p("""You can use the result of `CASE` to set a property(s) or a label(s) on a node or relationship.
I would rather use the plural form all the way:
```suggestion
      p("""You can use the result of `CASE` to set properties on a node or relationship.
```
and I find it particular that you pick the labels: We cannot bind a label to a variable as far as I know and if we bind the node/relationship to a variable, then we could do practically anything with that and not just assign a label.

Do you have a good example for that, that you could add?

2022-02-07 14:18 UTC, arnefischereit commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CaseExpressionsTest.scala
> +          resultTable()
Indentation
```suggestion
        ResultAssertions((r) => {
          assertStats(r, propertiesWritten = 5)
        })) {
        p("For more information about using the `SET` clause, see <<query-set>>.")
        resultTable()
```

2022-02-08 12:28 UTC, renetapopova commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CaseExpressionsTest.scala
> +      p("""You can use the result of `CASE` to set a property(s) or a label(s) on a node or relationship.
I don't have. I'll remove the label's part.

2022-02-08 15:42 UTC, arnefischereit approved these changes
LGTM

2022-02-08 16:02 UTC, merged