Update QueryPlanTest to use new indexes after Btree index removal.
neo4j/neo4j-documentation pull request #1453
Opened 2022-03-21 08:01 UTC by Dunfluff

2022-03-21 08:02 UTC, Dunfluff commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove btree from Documentation repo](https://trello.com/c/8igbfnYU/976-remove-btree-from-documentation-repo)

2022-03-21 13:21 UTC, Hunterness commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
> -      title = "Spatial distance searches (composite index)",
I'm guessing this test is called from somewhere to be included in the documentation, you need to remove it from there as well (goes for all removed tests)

2022-03-21 14:03 UTC, Dunfluff commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
> -      title = "Spatial distance searches (composite index)",
this has now been removed

2022-03-22 10:09 UTC, hedengran requested changes

2022-03-22 10:09 UTC, hedengran commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
> +      assertions = p => assertEquals(6, p.size)
I'm confused by this change. We still create as many indexes as before the changes, no?

2022-03-22 10:09 UTC, hedengran commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
> +      title = "Node RANGE index example",
For all titles that you have changed, you need to update the reference to the test in [query-tuning-indexes.adoc](https://github.com/neo4j/neo4j-documentation/pull/1453/files#diff-152aa72520c845a307b326d7e9ba8cf81f2fae263946f0677d97618a643d4031), just like you did with the spatial tests.

2022-03-22 10:09 UTC, hedengran commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
> +        "Text indexes are most efficient for `CONTAINS` and `ENDS WITH` but Text indexes are not as efficient as Range indexes for `=`, `IN` or `STARTS WITH`.",
```suggestion
        "Text indexes are optimized for `CONTAINS` and `ENDS WITH` and they're the only indexes that can solve those predicates.",
```

2022-03-22 10:09 UTC, hedengran commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
> +          "Text indexes are most efficient for `CONTAINS` and `ENDS WITH` but Text indexes are not as efficient as Range indexes for `=`, `IN` or `STARTS WITH`." +
```suggestion
          "Text indexes are optimized for `CONTAINS` and `ENDS WITH` and they're the only indexes that can solve those predicates." +
```

2022-03-22 10:09 UTC, hedengran commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
> +    executePreparationQueries(List("CREATE POINT INDEX FOR (p:Person) ON (p.location)"))
Why don't you create this at the top in `setupConstraintQueries`? It would then include that index in `list_indexes()` test, and I think that it would be nice to have a point index in that list.

2022-03-22 13:30 UTC, Dunfluff commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
> +      assertions = p => assertEquals(6, p.size)
I think that the `lineexecutePreparationQueries(List("create index for (p:Person) on (p.firstname)"))` does not create an index anymore since we already have `"CREATE RANGE INDEX FOR (p:Person) ON (p.firstname)",`. There might have been a difference before since we used btree.

2022-03-22 13:32 UTC, Hunterness commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
> +      assertions = p => assertEquals(6, p.size)
yes that will be the issue, we should maybe make sure we don't get such clashes between the class setup and the command tests though?

2022-03-22 13:34 UTC, Hunterness commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
> +        "Text indexes are most efficient for `CONTAINS` and `ENDS WITH` but Text indexes are not as efficient as Range indexes for `=`, `IN` or `STARTS WITH`.",
should it be mentioned that the text index only contains string properties in these examples? (maybe as the `optionalResultExplanation`?)

2022-03-22 13:36 UTC, Hunterness commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
> +    executePreparationQueries(List("CREATE POINT INDEX FOR (p:Person) ON (p.location)"))
My guess is that it clashes with the point indexes we create in the CREATE POINT INDEX tests, but we should be able to update the tests to not have the same label/property combinations

2022-03-22 15:34 UTC, Hunterness commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
> +      optionalResultExplanation = "Text indexes only index String values and therefor will not find other values.",
do we want similar things for the point index examples?

2022-03-23 09:11 UTC, hedengran approved these changes
Nice!

2022-03-29 12:23 UTC, AlexicaWright reviewed
Just a few editorial comments.

2022-03-29 12:23 UTC, AlexicaWright commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
> +        "Text indexes are optimized for `CONTAINS` and `ENDS WITH` and they're the only indexes that can solve those predicates.",
```suggestion
        "Text indexes are optimized for `CONTAINS` and `ENDS WITH` and they are the only indexes that can solve those predicates.",
```

2022-03-29 12:23 UTC, AlexicaWright commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
> +      optionalResultExplanation = "Text indexes only index String values and therefor will not find other values.",
```suggestion
      optionalResultExplanation = "Text indexes only index String values and therefore do not find other values.",
```

2022-03-29 12:23 UTC, AlexicaWright commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
> +          "Text indexes are optimized for `CONTAINS` and `ENDS WITH` and they're the only indexes that can solve those predicates." +
```suggestion
          "Text indexes are optimized for `CONTAINS` and `ENDS WITH` and they are the only indexes that can solve those predicates." +
```

2022-03-29 12:23 UTC, AlexicaWright commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
> +      optionalResultExplanation = "Text indexes only index String values and therefor will not find other values.",
```suggestion
      optionalResultExplanation = "Text indexes only index String values and therefore do not find other values.",
```

2022-03-29 13:21 UTC, AlexicaWright approved these changes
👍  LGTM! Thanks @Dunfluff !

2022-03-29 14:09 UTC, merged