Document new text index provider and deprecation of the old one
neo4j/neo4j-documentation pull request #1626
Opened 2022-09-28 15:39 UTC by Hunterness

2022-10-12 15:06 UTC, mnd999 requested changes

2022-10-12 15:06 UTC, mnd999 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SchemaIndexTest.scala
> +          |The valid values for the index provider is `$textProvider` and `$oldTextProvider` (deprecated), the default value is $textProvider.""".stripMargin,
```suggestion
          |The valid values for the index provider are `$textProvider` and `$oldTextProvider` (deprecated). The default provider is $textProvider.""".stripMargin,
```

2022-10-13 09:00 UTC, mnd999 approved these changes

2022-10-13 09:18 UTC, AlexicaWright reviewed
One small comment only.

2022-10-13 09:18 UTC, AlexicaWright commented on cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
> +A new text index provider is available, `text-2.0`. This is also the default provider if none is given.
```suggestion
A new text index provider is available, `text-2.0`. 
This is also the default provider if none is given.
```

2022-10-13 09:20 UTC, AlexicaWright approved these changes
👍

2022-10-13 10:23 UTC, merged