Update explanation for predicate functions when used with null values.
neo4j/neo4j-documentation pull request #1633
Opened 2022-10-03 14:57 UTC by gem-neo4j

Fixes https://github.com/neo4j/neo4j/issues/12946

2022-10-03 14:58 UTC, gem-neo4j commented
![](https://github.trello.services/images/mini-trello-icon.png) [The doc about in list predicates is not correct](https://trello.com/c/LxKIkvNL/314-the-doc-about-in-list-predicates-is-not-correct)

2022-10-05 09:24 UTC, Lojjs requested changes
I think we didn't discuss this deep enough in 3 minutes 😆 . I did some experiments and gave you suggestions on more accurate wording. Also I think I might have found a bug. The examples are more for your understanding, you don't have to include them in the docs necessarily.

2022-10-05 09:24 UTC, Lojjs commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PredicateFunctionsTest.scala
> +          #`null` is returned if the list is `null` or if one of the comparisons evaluates to `null`.""".stripMargin('#'))
My experiments show

```
1. RETURN all(x IN [null] WHERE x = 1) => null
2. RETURN all(x IN [null, 1] WHERE x = 1) => null
3. RETURN all(x IN [1, null] WHERE x = 1) => null
4. RETURN all(x IN [2,null] WHERE x = 1) => false
5. RETURN all(x IN [null, 2] WHERE x = 1) => null
6. RETURN all(x IN [ 1, null, 2] WHERE x = 1) => null
```

I can see the logic in that 4. would return `false` as regardless of what unknown the `null` stands for, all elements cannot be 1 if there is a 2. But then I wonder why 5. and 6. doesn't give the same result? That feels a bit like a Cypher bug to me... Do you agree?

2022-10-05 09:24 UTC, Lojjs commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PredicateFunctionsTest.scala
> +          #`null` is returned if the list is `null` or if one of the comparisons evaluates to `null` and no other has evaluated to true.""".stripMargin('#'))
My experiments show

```
1. RETURN any(x IN [null] WHERE x = 1) => null
2. RETURN any(x IN [null, 1] WHERE x = 1) => true
3. RETURN any(x IN [1, null] WHERE x = 1) => true
4. RETURN any(x IN [2,null] WHERE x = 1) => null
5. RETURN any(x IN [null, 2] WHERE x = 1) => null
6. RETURN any(x IN [1, null, 2] WHERE x = 1) => true
```

I think that matches with your sentence, so here I just have a suggestion of a better wording:

```suggestion
          #`null` is returned if the list is `null`, or if the predicate evaluates to `null` for at least one element and does not evaluate to `true` for any other element.""".stripMargin('#'))
```

2022-10-05 09:24 UTC, Lojjs commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PredicateFunctionsTest.scala
> +          #`null` is returned if the list is `null` or if one of the comparisons evaluates to `null`.""".stripMargin('#'))
As expected, this is `null` for all the 6 examples from my experiment, but if you have a `null` and more than one element that fulfills the predicate e.g. `RETURN single(x IN [1, null, 1] WHERE x = 1)` that return `false`.

```suggestion
          #`null` is returned if the list is `null`, or if the predicate evaluates to `null` for at least one element and `true` for max one element.""".stripMargin('#'))
```

2022-10-05 09:24 UTC, Lojjs commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PredicateFunctionsTest.scala
> +          #`null` is returned if the list is `null` or if one of the comparisons evaluates to `null` and no other has evaluated to true.""".stripMargin('#'))
My experiments show

```
1. RETURN none(x IN [null] WHERE x = 1) => null
2. RETURN none(x IN [null, 1] WHERE x = 1) => false
3. RETURN none(x IN [1, null] WHERE x = 1) => false
4. RETURN none(x IN [2,null] WHERE x = 1) => null
5. RETURN none(x IN [null, 2] WHERE x = 1) => null
6. RETURN none(x IN [1, null, 2] WHERE x = 1) => false
```

This also seems to match with your sentence, so just same wording suggestion as above

```suggestion
          #`null` is returned if the list is `null`, or if the predicate evaluates to `null` for at least one element and does not evaluate to `true` for any other element.""".stripMargin('#'))
```

2022-10-07 07:10 UTC, gem-neo4j commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PredicateFunctionsTest.scala
> +          #`null` is returned if the list is `null` or if one of the comparisons evaluates to `null`.""".stripMargin('#'))
Yeah, that sounds like a bug I agree!

2022-10-07 07:42 UTC, Lojjs approved these changes

2022-11-22 15:42 UTC, davidoliverSP2 commented
This has been recreated in the new repository (https://github.com/neo4j/docs-cypher/pull/226)

As we are no longer publishing from this repo, I'll close this PR

2022-11-22 15:42 UTC, closed without merging