Avg and sum of Durations
neo4j/neo4j-documentation pull request #217
Opened 2018-05-18 10:55 UTC by sherfert

Corresponding product PR: https://github.com/neo4j/neo4j/pull/11808

2018-05-18 11:22 UTC, Lojjs requested changes
You have done some calculation errors in your examples and missed to add `- Numeric values` in one place. You are also mixing btween `duartions` and `Durations`, e.g. `returns the average of a set of Durations` but `returns the sum of a set of durations`

2018-05-18 11:22 UTC, Lojjs commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/AggregatingFunctionsTest.scala
> +    section("sum() - Numeric values", "functions-sum") {
You forgot to do this change to the old avg section

2018-05-18 11:22 UTC, Lojjs commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/AggregatingFunctionsTest.scala
> +        r.toList.head("avg(dur)") should equal(DurationValue.duration(0, 1, 2 * 60 + 22, 500000000))
Shouldn't it be `2 * 3600 + 22` seconds?

2018-05-18 11:22 UTC, Lojjs commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/AggregatingFunctionsTest.scala
> +        r.toList.head("sum(dur)") should equal(DurationValue.duration(0, 3, 4 * 60 + 45, 0))
Shouldn't it be `DurationValue.duration(0, 2, 4 * 3600 + 45, 0)` ?

2018-05-23 12:00 UTC, Lojjs approved these changes

2018-06-07 12:10 UTC, jjaderberg approved these changes
LGTM

2018-06-07 12:11 UTC, merged