Made clearer the text pertaining to providing x and y to WGS-84
neo4j/neo4j-documentation pull request #238
Opened 2018-08-01 09:04 UTC by petraselmer

Addresses [https://github.com/neo4j/neo4j/issues/11977](https://github.com/neo4j/neo4j/issues/11977)

2018-08-01 16:08 UTC, craigtaverner requested changes

2018-08-01 16:08 UTC, craigtaverner commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SpatialFunctionsTest.scala
> +      considerations("If any argument provided to `point()` is `null`, `null` will be returned.", "If the coordinates are specified using `latitude` and `longitude`, the `crs` or `srid` fields are op
The last sentence now feels redundant.

2018-08-01 16:08 UTC, craigtaverner commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SpatialFunctionsTest.scala
> +      considerations("If any argument provided to `point()` is `null`, `null` will be returned.", "If the `height/z` key and value is not provided, a 2D point in the _WGS 84_ CRS will be returned.",
The last sentence now feels redundant.

2018-08-02 08:37 UTC, petraselmer commented
@craigtaverner addressed your review.

2018-08-02 11:06 UTC, craigtaverner requested changes
We started making the suggested changes and realised they actually do not work. These suggestions make sense if the considerations section was for a general section on the point function, which it is not. There are four sections, one for each of the CRS. The thinking is that each user would want to know how to make a point for their CRS of interest. The consideration sections are all different, each specific to the CRS under consideration, and written from that perspective. The asymmetry observed here is deliberate and correct.

2018-08-02 11:06 UTC, craigtaverner commented
We started making the suggested changes and realised they actually do not work. These suggestions make sense if the considerations section was for a general section on the point function, which it is not. There are four sections, one for each of the CRS. The thinking is that each user would want to know how to make a point for their CRS of interest. The consideration sections are all different, each specific to the CRS under consideration, and written from that perspective. The asymmetry observed here is deliberate and correct.

2018-08-02 11:06 UTC, closed without merging