3.5 index backed order by
neo4j/neo4j-documentation pull request #252
Opened 2018-09-06 20:19 UTC by craigtaverner

Documentation for the performance optimization provided by index-backed property lookup and index-backed order-by.

2018-09-06 21:06 UTC, jexp commented on cypher/cypher-docs/src/docs/graphgists/query-tuning/advanced-query-tuning-example.asciidoc
> +CREATE INDEX ON :Person(name)
add `call dbms.awaitIndexes(timeout)`?

2018-09-07 13:24 UTC, craigtaverner commented on cypher/cypher-docs/src/docs/graphgists/query-tuning/advanced-query-tuning-example.asciidoc
> +CREATE INDEX ON :Person(name)
That did not help. I actually had to use a `USING INDEX` hint to get the queries to work.

2018-09-07 14:43 UTC, petraselmer requested changes
@craigtaverner can you also add a 3.5 section to this file: https://github.com/neo4j/neo4j-documentation/blob/3.5/cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc  (and add a line about the IBO)

Thanks!

2018-09-07 14:43 UTC, petraselmer commented on cypher/cypher-docs/src/docs/dev/query-tuning.asciidoc
> +Any Cypher query that searches for Nodes with a specific label and some predicate on the property (equality, range or existence) will be planned to use
I wouldn't title-case Nodes...

2018-09-10 09:10 UTC, petraselmer commented
👍

2018-09-10 10:56 UTC, petraselmer approved these changes

2018-09-10 10:58 UTC, merged