Add Cypher deprecations
neo4j/neo4j-documentation pull request #263
Opened 2018-09-25 17:34 UTC by fickludd

Add deprecation warnings to

 * rule planner
 * compiled runtime
 * extract, filter, all, any, none, single

I noticed that these things are also in the refcard, but am unsure of how to deprecate content there, or if it's actually better to just remove deprecated things from there and replace them with the relevant list-comprehension. Which conveniently bring me to wonder: is there any place where list-comprehensions (e.g. `[x IN xs WHERE x.name = "johan" | x.age / 10]`) are presented. I couldn't really find it, maybe we should add more on that.

2018-09-27 11:02 UTC, petraselmer requested changes

2018-09-27 11:02 UTC, petraselmer commented on cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
> +| `CYPHER runtime=compiled` (Compiled runtime)    | Functionality | Deprecated | The compiled runtime will be discontinued on the next major release. It might still be used for default queries in ord
"discontinued on the" -> "discontinued in the"

2018-09-27 11:02 UTC, petraselmer commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PredicateFunctionsTest.scala
> +      p("The functions `all()`, `any()`, `none()` and `single()` have been deprecated and will be removed in a future release. Consider using a list-comprehension (e.g. `[x IN xs WHERE predicate | ex
"using a list-comprehension" -> "using a list comprehension"

2018-09-27 11:02 UTC, petraselmer commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ListFunctionsTest.scala
> +      p("The functions `extract()` and `filter()` have been deprecated and will be removed in a future release. Consider using a list comprehension (e.g. `[x IN xs WHERE predicate | extraction]`) ins
I wonder if it would be a good idea to add `[role=deprecated]` (as you did above, for the rule planner in query tuning) to the detailed text for `extract` and `filter`? People may jump to the details immediately without going from the top of the page, and it doesn't hurt to really, really drive home that these functions are on their way out. 

I would also add, to the function detail section - your second sentence "Consider using a list com..." so that people know how to achieve the same functionality

2018-09-27 11:02 UTC, petraselmer commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ListFunctionsTest.scala
> +      p("The functions `extract()` and `filter()` have been deprecated and will be removed in a future release. Consider using a list comprehension (e.g. `[x IN xs WHERE predicate | extraction]`) ins
I also would link "list comprehension" to the relevant section in the manual. It's not much - i.e. it is far from perfect or even good - but at least it provides context and extra reading for those users who haven't used list comprehensions. 

The way to do this is to replace "list comprehension" with "<<cypher-list-comprehension, list comprehension>>"

2018-09-27 11:02 UTC, petraselmer commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PredicateFunctionsTest.scala
> +      p("The functions `all()`, `any()`, `none()` and `single()` have been deprecated and will be removed in a future release. Consider using a list-comprehension (e.g. `[x IN xs WHERE predicate | ex
I wonder if it would be a good idea to add [role=deprecated] (as you did above, for the rule planner in query tuning) to the detailed text for all, any etc? People may jump to the details immediately without going from the top of the page, and it doesn't hurt to really, really drive home that these functions are on their way out.

I would also add, to the function detail section - your second sentence "Consider using a list com..." so that people know how to achieve the same functionality

2018-09-27 11:02 UTC, petraselmer commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PredicateFunctionsTest.scala
> +      p("The functions `all()`, `any()`, `none()` and `single()` have been deprecated and will be removed in a future release. Consider using a list-comprehension (e.g. `[x IN xs WHERE predicate | ex
I also would link "list comprehension" to the relevant section in the manual. It's not much - i.e. it is far from perfect or even good - but at least it provides context and extra reading for those users who haven't used list comprehensions.

The way to do this is to replace "list comprehension" with "<<cypher-list-comprehension, list comprehension>>"

2018-09-27 11:02 UTC, petraselmer commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ListFunctionsTest.scala
> +      p("The functions `extract()` and `filter()` have been deprecated and will be removed in a future release. Consider using a list comprehension (e.g. `[x IN xs WHERE predicate | extraction]`) ins
Also, can you give an actual example using a list comprehension that achieves the same effect? Probably sufficient to do it for just one of `extract` and `filter`; i.e. as long as there is something on the page readers can see.

2018-09-27 11:02 UTC, petraselmer commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PredicateFunctionsTest.scala
> +      p("The functions `all()`, `any()`, `none()` and `single()` have been deprecated and will be removed in a future release. Consider using a list-comprehension (e.g. `[x IN xs WHERE predicate | ex
Also, can you give an actual example using a list comprehension that achieves the same effect? Probably sufficient to do it for just one of the 4 functions; i.e. as long as there is something on the page readers can see.

2018-10-01 10:51 UTC, mariascharin commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PredicateFunctionsTest.scala
> +      p("The functions `all()`, `any()`, `none()` and `single()` have been deprecated and will be removed in a future release. Consider using a list-comprehension (e.g. `[x IN xs WHERE predicate | ex
@fickludd I propose removing deprecated stuff from the refcard. It is the Cypher Manual that is the comprehensive and authoritative reference.

2018-10-05 09:15 UTC, fickludd commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PredicateFunctionsTest.scala
> +      p("The functions `all()`, `any()`, `none()` and `single()` have been deprecated and will be removed in a future release. Consider using a list-comprehension (e.g. `[x IN xs WHERE predicate | ex
Thank you both! For the list-predicates (all, any, single and none) we have actually swung around to not wanting to deprecate these anymore, so changing this PR to reflect that.

2018-10-10 07:40 UTC, petraselmer approved these changes

2018-10-10 07:42 UTC, merged