Describe limitations of composite indexes better
neo4j/neo4j-documentation pull request #281
Opened 2018-12-03 14:16 UTC by Lojjs

Also clarify that you cannot fallback from a composite index to a single one like in SQL

2018-12-07 20:09 UTC, craigtaverner requested changes
The complete rendered docs do not include the new content. I think the section id `schema-index-single-vs-composite-index` need to be included somewhere to make this active.

2018-12-10 16:16 UTC, craigtaverner approved these changes

2018-12-11 07:38 UTC, Lojjs reviewed
I found an error in your text, otherwise it looks fine (apart from that I cannot see the rendering...)

2018-12-11 07:38 UTC, Lojjs commented on cypher/cypher-docs/src/docs/dev/ql/schema-index/index.asciidoc
> +If there are predicates on only a subset of the indexed properties, the Cypher will not be able to use the composite index.
This seems clearer, but you should remove `the` in `the Cypher`

2018-12-11 10:42 UTC, merged