Get (back) the real default for DURATION settings
neo4j/neo4j-documentation pull request #34
Opened 2017-02-22 22:01 UTC by jjaderberg

Based on neo4j/neo4j#8875

2017-02-23 10:36 UTC, spacecowboy requested changes

2017-02-23 10:36 UTC, spacecowboy commented on manual/doctools/src/main/java/org/neo4j/doc/SettingsDescription.java
> +import java.util.*;
glob-import here (change your intellij settings to avoid glob-imports)

2017-02-23 10:36 UTC, spacecowboy commented on manual/doctools/src/main/java/org/neo4j/doc/SettingsDescription.java
> +                        defaultValue = Long.toString(TimeUtil.DEFAULT_TIME_UNIT.convert(Long.valueOf(defaultValue), TimeUnit.MILLISECONDS));
I think we should add the unit to the string also, for extra clarity

2017-02-24 20:26 UTC, jjaderberg commented on manual/doctools/src/main/java/org/neo4j/doc/SettingsDescription.java
> +import java.util.*;
sure

2017-02-24 20:28 UTC, jjaderberg commented on manual/doctools/src/main/java/org/neo4j/doc/SettingsDescription.java
> +                        defaultValue = Long.toString(TimeUtil.DEFAULT_TIME_UNIT.convert(Long.valueOf(defaultValue), TimeUnit.MILLISECONDS));
there's no immediate way to get the unit from TimeUtil. it's a good-to-have so let's defer it to the new tool in 3.2

2017-02-24 21:32 UTC, merged