Removing repository declarations for m2.neo4j.org
neo4j/neo4j-documentation pull request #423
Opened 2019-10-10 13:57 UTC by lassewesth

These declarations at best make m2.neo4j.org a SPOF when building docs. Instead, let Maven Central and it's CDN provide released dependencies.

The problem you have been seeing occur whenever Maven sees a dependency declared as a snapshot version. Because it then picks the abandoned m2.neo4j.org to resolve it, fails, and _reports m2.neo4j.org as the failure_ which is just hella misleading.

This change solves all the above mentioned problems once and or all 🎉 

This can be forward merged to 3.2 and 3.3 which have similar repository declarations.

2019-10-10 18:56 UTC, jjaderberg requested changes
Needs to resolve Neo4j parent from somewhere: https://github.com/neo4j/neo4j-documentation/blob/3.1/pom.xml#L4-L8

Who needs to build this for 3.1..3.3 anyway? In 3.4 parent is gone.

If this really needs to work maybe freeze the version to something released?

2019-10-10 21:23 UTC, jjaderberg approved these changes

2019-10-10 21:23 UTC, jjaderberg commented
If it's acceptable to freeze the Neo4j dependency version, this should work.

2019-10-11 10:11 UTC, lassewesth commented
Who's the arbiter?

2019-10-18 19:36 UTC, jjaderberg commented
@mariascharin @davidoliverSP2 @AlexicaWright I think this is a good change. Is it ok with you if I merge this?

2019-10-21 13:10 UTC, mariascharin commented
@jjaderberg You are welcome to it if you have time :) Thank you!

2020-03-02 13:08 UTC, mariascharin commented
@lassewesth I am replacing this one with #520 since we have stopped building any docs previous to 3.4. With that, there shouldn't be anything remaining from Docs point of view that depends on m2.neo4j.org.

2020-03-02 13:09 UTC, mariascharin commented
Superseded by #520

2020-03-02 13:09 UTC, closed without merging