Add DEFAULT DATABASE to the database administration section.
neo4j/neo4j-documentation pull request #509
Opened 2020-02-18 16:17 UTC by Lojjs

2020-02-19 09:52 UTC, Hunterness approved these changes
The database privilege image is also updated to reflect this and other 4.1 changes: https://github.com/neo-technology/neo4j-manual-modeling/pull/1030

2020-02-25 09:16 UTC, Hunterness requested changes
When updating docs for the compound work I found more places where this maybe should have been updated

2020-02-25 09:16 UTC, Hunterness commented on cypher/cypher-docs/src/docs/dev/ql/administration/security/database/admin-database-syntax.asciidoc
> +| Allow the specified role or roles to access the default database, the database `name` or all databases
There are individual files for some of the different privileges, maybe they should be updated too?

```
database/all-management-syntax.asciidoc
database/constraint-management-syntax.asciidoc
database/deny-database-access-syntax.asciidoc
database/deny-database-start-syntax.asciidoc
database/deny-database-stop-syntax.asciidoc
database/grant-database-access-syntax.asciidoc
database/grant-database-start-syntax.asciidoc
database/grant-database-stop-syntax.asciidoc
database/index-management-syntax.asciidoc
database/name-management-syntax.asciidoc
```

2020-02-26 07:57 UTC, Hunterness approved these changes

2020-02-28 11:25 UTC, davidoliverSP2 approved these changes
Thanks @Lojjs 👍 

The only feedback I have is that I noticed on quite a few occasions the user of dbms in lower case - I think it should be consistent with [the introduction to databases and graphs](https://neo4j.com/docs/cypher-manual/4.1-preview/introduction/neo4j-databases-graphs/), and be in upper case. However, I don't think it's worth changing in this PR, as I saw multiple instances of it in the manual - we'll fix in another PR.

2020-02-28 11:25 UTC, merged