Sub-menu in the Operators page
neo4j/neo4j-documentation pull request #564
Opened 2020-05-02 09:09 UTC by renetapopova

Replaces #562

2020-05-04 12:49 UTC, AlexicaWright reviewed
Thank you @renetapopova , lots of work! As per the discussion on the Trello card, I am on the fence whether this is an improvement or not. There are so many operators that one doesn't get a good overview even with a sub-menu. However, one do get a sense of how many there are and I guess that counts. Bottom line, I say let's merge this!

2020-05-06 15:48 UTC, renetapopova commented
@davidoliverSP2 please review it

2020-05-07 06:39 UTC, davidoliverSP2 requested changes
Hi @renetapopova - this looks good, but there is something odd going on with the index file in this section - if you build this and look at Chapter 7. Execution plans, there is a lot of content building, and the toc doesn't include this page.

2020-05-07 06:39 UTC, davidoliverSP2 commented on cypher/cypher-docs/src/docs/dev/execution-plan-groups/operators.asciidoc
> += Execution plan operators in details
I think this should be 

> Execution plan operators in detail

2020-05-12 07:58 UTC, davidoliverSP2 approved these changes
Thanks @renetapopova - this is excellent 👍 

There is still an oddity with the back and forward links, so I created https://github.com/neo-technology/neo4j-manual-modeling/pull/1122 to update the content map.

2020-05-12 10:39 UTC, merged