Update octal syntax
neo4j/neo4j-documentation pull request #627
Opened 2020-07-16 14:46 UTC by hedengran

2020-07-17 08:09 UTC, Hunterness commented on cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
> +| `0o...`                     | Syntax        | Added   | Cypher will now interpret literals with prefix `0o` as an octal integer literal.
should also add that `0X..` is deprecated

2020-07-24 12:10 UTC, SaschaPeukert requested changes

2020-07-24 12:10 UTC, SaschaPeukert commented on cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
> +| `0...`                      | Syntax        | Deprecated   | Replaced by `0...` (see above).
```suggestion
| `0...`                      | Syntax        | Deprecated   | Replaced by `0o...` (see above).
```

2020-07-27 14:05 UTC, hedengran commented on cypher/cypher-docs/src/docs/dev/deprecations-additions-and-compatibility.asciidoc
> +| `0...`                      | Syntax        | Deprecated   | Replaced by `0...` (see above).
Good catch, thanks!

2020-07-28 07:55 UTC, SaschaPeukert approved these changes

2020-07-28 10:20 UTC, merged