Document encrypted password command
neo4j/neo4j-documentation pull request #656
Opened 2020-09-10 06:47 UTC by hedengran

Documentation for the encrypted password command, and a commit with small fixes for broken links.

2020-09-10 12:29 UTC, mnd999 requested changes
Looks like a few extra changes may have snuck in. Also, you should probably label this "Depends w. other PR" and link to the code PR as it's currently not building due to the change not being merged yet.

2020-09-10 12:29 UTC, mnd999 commented on cypher/cypher-docs/src/docs/dev/glossary.asciidoc
> +|<<functions-round1, round()>>                   | Numeric           | Returns the value of the given number rounded to the nearest integer, with half-way values always rounded up.
This doesn't seem related to encrypted passwords. Has something unrelated got mixed up in this PR?

2020-09-10 12:29 UTC, mnd999 commented on cypher/cypher-docs/src/docs/dev/ql/functions/index.asciidoc
> +|<<functions-round1, round()>>                                    | Returns the value of the given number rounded to the nearest integer, with half-way values always rounded up.
Same, should this be part of this PR?

2020-09-10 12:29 UTC, mnd999 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityUserAndRoleManagementTest.scala
> +        p("The `password` can either be a string value or a string parameter, and is not allowed to be identical to the old password. " +
```suggestion
        p("The `password` can either be a string value or a string parameter, and must not be identical to the old password. " +
```

2020-09-10 12:29 UTC, mnd999 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityPrivilegesTest.scala
> +          |only a reduction in the apparent graph size. We will use _'allows'_ to refer to the consequence of <<administration-security-writes, write privileges>>
Is this related to this PR?

2020-09-10 12:29 UTC, mnd999 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/FulltextIndexTest.scala
> +      p("For information on how to configure full-text indexes, refer to <<operations-manual#index-configuration-fulltext,  Operations Manual -> Indexes to support full-text search>>.")
Is this related to to this PR?

2020-09-10 12:29 UTC, mnd999 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityUserAndRoleManagementTest.scala
> +          "With `ENCRYPTED`, the password string is expected to be on the format `<encryption-version>,<hash>,<salt>`."
```suggestion
          "The optional `ENCRYPTED` can be used to update a user's password when the plaintext password is unknown but the encrypted password is available (e.g. from a database backup). " +
          "With `ENCRYPTED`, the password string is expected to be on the format `<encryption-version>,<hash>,<salt>`."
```

2020-09-10 12:29 UTC, mnd999 commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityUserAndRoleManagementTest.scala
> +          "The optional `ENCRYPTED` can be used to create a user when the plaintext password is unknown but the encrypted password is available. " +
```suggestion
          "The optional `ENCRYPTED` can be used to create a user when the plaintext password is unknown but the encrypted password is available (e.g. from a database backup). " +
```

2020-09-10 13:33 UTC, hedengran commented
> Looks like a few extra changes may have snuck in. 

As I wrote in the PR description, the PR also includes an additional commit where I fixed some broken links.

2020-09-17 12:39 UTC, mnd999 approved these changes

2020-09-17 12:42 UTC, merged