Document isEmpty function.
neo4j/neo4j-documentation pull request #741
Opened 2020-11-16 09:11 UTC by sherfert

Must wait for https://github.com/neo-technology/neo4j/pull/7897 to get merged.

2020-11-17 09:19 UTC, tobias-johansson requested changes

2020-11-17 09:19 UTC, tobias-johansson commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/PredicateFunctionsTest.scala
> +        p("The ages of all nodes with that have the empty string as the `eyes` property.")
It only occurred to me now, that `WHERE isEmpty(n.eyes)` will keep rows where `n.eyes = ''` but drop rows where `n.eyes = null` (i.e. unset). That might seem surprising to a user, so perhaps it should be called out here somewhere?

2020-11-19 07:39 UTC, tobias-johansson approved these changes

2020-11-23 11:05 UTC, sherfert commented
@davidoliverSP2 Looks like there is a test failing because of a product bug. Let's hold off with merging this PR, I'll let you know when we have fixed the bug in the product.

2020-11-30 11:00 UTC, davidoliverSP2 commented
@sherfert this looks like the dependant PR in neo4j (neo-technology/neo4j#7897) is now merged. Is this one now good to go?

2020-11-30 12:04 UTC, sherfert commented
@davidoliverSP2 yes.

2020-11-30 13:20 UTC, merged