Documentation for CREATE / ALTER USER SET DEFAULT DATABASE
neo4j/neo4j-documentation pull request #745
Opened 2020-11-16 12:16 UTC by mnd999

* Documentation for CREATE / ALTER USER SET DEFAULT DATABASE which allows an administrator to set a default database on a per-user basis. Also, document permissions for allowing this.

* Some cleanup, prevent backup port in tests clashing with running Neo4j

Depends on: https://github.com/neo-technology/neo4j/pull/7866

2020-11-20 10:00 UTC, OliviaYtterbrink requested changes
Needs to be updated to reflect the changes in how default database is working

2020-11-24 11:34 UTC, mnd999 commented
@OliviaYtterbrink I have update the docs to reflect the changes to the PRD

2020-11-24 15:17 UTC, OliviaYtterbrink approved these changes
Looks good.

2020-11-24 15:17 UTC, OliviaYtterbrink commented on cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/SecurityUserAndRoleManagementTest.scala
> +        query("SHOW USERS YIELD user, suspended, passwordChangeRequired, roles, defaultDatabase WHERE user = 'jake'", assertUsersShown(Seq("jake"))) {
Would've been nice if we could have a stronger assertion here.

2020-12-07 14:43 UTC, davidoliverSP2 approved these changes
Thanks @mnd999 👍

2020-12-07 14:43 UTC, merged