Document YIELD and WHERE for SHOW INDEXES
neo4j/neo4j-documentation pull request #922
Opened 2021-02-12 14:52 UTC by Hunterness

Also deprecate BRIEF and VERBOSE keywords.

Depends on https://github.com/neo-technology/neo4j/pull/8855

2021-02-15 10:25 UTC, OliviaYtterbrink requested changes

2021-02-15 10:25 UTC, OliviaYtterbrink commented on cypher/cypher-prettifier/src/test/scala/org/neo4j/cypher/docgen/tooling/PrettifierTest.scala
> +  test("may break SHOW INDEXES") {
I think this should be split in two tests, one for breaks and one for the old behaviour
and shouldn't `show indexes brief` be here as well?

2021-02-15 13:40 UTC, Hunterness commented on cypher/cypher-prettifier/src/test/scala/org/neo4j/cypher/docgen/tooling/PrettifierTest.scala
> +  test("may break SHOW INDEXES") {
what about line 76?

2021-02-15 13:41 UTC, Hunterness commented on cypher/cypher-prettifier/src/test/scala/org/neo4j/cypher/docgen/tooling/PrettifierTest.scala
> +  test("may break SHOW INDEXES") {
but yes, I should probably split it

2021-02-15 15:46 UTC, OliviaYtterbrink approved these changes

2021-02-25 09:36 UTC, Hunterness commented on cypher/cypher-docs/src/docs/dev/ql/administration/indexes-for-search-performance/index.asciidoc
> +    [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
Update to match https://trello.com/c/XIambksk/2372-update-docs-to-have-valid-where-yield-return-in-show-syntax-descriptions

2021-03-01 11:23 UTC, martin-neotech approved these changes
Thanks

2021-03-01 13:21 UTC, merged